# Generated by Django 5.1.6 on 2025-10-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills_desc', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('med_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normalized_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('salary_period', models.CharField(default='yearly', max_length=20)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('job_posting_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Business', 'Business'), ('Medicine', 'Medicine'), ('Arts', 'Arts'), ('Sciences', 'Sciences'), ('Other', 'Other')], max_length=50)),
                ('gpa', models.FloatField()),
                ('extracurricular_activities', models.IntegerField(default=0)),
                ('internships', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('leadership_positions', models.IntegerField(default=0)),
                ('research_experience', models.IntegerField(default=0)),
                ('coding_skills', models.IntegerField(default=0)),
                ('communication_skills', models.IntegerField(default=0)),
                ('problem_solving_skills', models.IntegerField(default=0)),
                ('teamwork_skills', models.IntegerField(default=0)),
                ('analytical_skills', models.IntegerField(default=0)),
                ('presentation_skills', models.IntegerField(default=0)),
                ('networking_skills', models.IntegerField(default=0)),
                ('industry_certifications', models.IntegerField(default=0)),
                ('recommended_career', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
