# Generated by Django 5.1.6 on 2025-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_custom_university_alter_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
