# Generated by Django 5.1.6 on 2025-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='other_field',
            field=models.CharField(blank=True, help_text="If you selected 'Other', please specify.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='field',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Art', 'Art'), ('Biology', 'Biology'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Law', 'Law'), ('Marketing', 'Marketing'), ('Medicine', 'Medicine'), ('Music', 'Music'), ('Physics', 'Physics'), ('Psychology', 'Psychology'), ('Other', 'Other')], max_length=50),
        ),
    ]
