# Generated by Django 5.1.6 on 2025-02-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_studentdetails_user_user_city_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletransition',
            name='new_role',
            field=models.CharField(choices=[('KenSAP', 'KenSAP Student'), ('Undergrad', 'Undergraduate'), ('Alumni', 'Alumni'), ('CareerMember', 'Career Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roletransition',
            name='old_role',
            field=models.CharField(choices=[('KenSAP', 'KenSAP Student'), ('Undergrad', 'Undergraduate'), ('Alumni', 'Alumni'), ('CareerMember', 'Career Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('KenSAP', 'KenSAP Student'), ('Undergrad', 'Undergraduate'), ('Alumni', 'Alumni'), ('CareerMember', 'Career Member')], default='KenSAP', max_length=20),
        ),
    ]
