# Generated by Django 5.1.6 on 2025-11-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Extracurricular', 'Extracurricular'), ('Internship', 'Internship'), ('Project', 'Project'), ('Leadership', 'Leadership'), ('Research', 'Research'), ('Industry', 'Industry')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.assessment')),
            ],
        ),
    ]
